version: 2.1

orbs:
  docker: circleci/docker@2.1.0

jobs:
  build-and-run:
    docker:
      - image: cimg/base:current # Using the CircleCI base image
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Pull custom image
          command: docker pull nginx

      - run:
          name: Build and push
          command: |
            docker build -t test .
            docker ps


workflows:
  version: 2
  build_and_run_workflow:
    jobs:
      - build-and-run
