version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.5
  aws-ecr: circleci/aws-ecr@7.3.0
  docker: circleci/docker@2.7.0

jobs:
  build_and_push:
    machine:
      image: ubuntu-2004:2023.07.1  # Uses a machine executor for native Docker support
    steps:
      - checkout
      - run:
          name: "Test: Print ROLE_ARN"
          command: "echo ${ROLE_ARN}"
          
      - aws-cli/setup:
          role-arn: ROLE_ARN
          aws-region: REGION
          role-session-name: "example-session"
          session-duration: "1800"

      # Login to ECR using the AWS ECR Orb
      - aws-ecr/ecr-login:
          region: REGION

      # # Build Docker image
      # - docker/build:
      #     image: "your-docker-image-name"   # Replace with your image name
      #     tag: "latest"  # Tag your image; you can also use versioning if needed

      # # Push Docker image to ECR
      # - aws-ecr/push-image:
      #     repo: "your-ecr-repo-name"  # Replace with your ECR repo name
      #     image: "your-docker-image-name"
      #     tag: "latest"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_push
