version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.1
  aws-ecr: circleci/aws-ecr@9.0.1
  docker: circleci/docker@2.1.0

jobs:
  build-push:
    docker:
      - image: cimg/aws:2022.06
    steps:
      - checkout
      - aws-cli/setup:
          role_arn: "arn:aws:iam::654654311376:role/CircleCI_OIDC"

      - aws-ecr/build-and-push-image:
          repo: "test"
          tag: "${CIRCLE_SHA1}"

workflows:
  version: 2
  build_and_push:
    jobs:
      - build-push
