version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:current
      - image: docker
        environment:
          DOCKER_OPTS: "--tlsverify=false"  # Example argument
    resource_class: vieer-rubrik/tester
    steps:
      - run: echo "Hi I'm on a Container Runner!"
workflows:
  build-workflow:
    jobs:
      - build