version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:current
      - image: docker:dind
        user: root
        # entrypoint : ["sh -c dockerd-entrypoint.sh --tlsverify=false"]
      
    resource_class: vieer-rubrik/tester
    steps:
      - run: echo "Hi I'm on a Container Runner!"
      - run : |
          apt update && apt install -y curl && \
          curl -fsSL $DOCKER_URL/docker-$DOCKER_VERSION.tgz | \
          tar zxvf - --strip-components=1 -C /usr/bin docker/docker

workflows:
  build-workflow:
    jobs:
      - build